### ISSUE TITLE
Call the right CSS file name in HTML

### ISSUE THREAD

**Issue by 0x00memex** [danilowoz/wipe.css#1]

**Comment by danilowoz** [comment]
It'll be applied to every element: 

```css
* {
  margin: 0; /* 1 */
  padding: 0; /* 1 */
  background-repeat: no-repeat; /* 1 */
  box-sizing: inherit; /* 2 */
}
```
https://github.com/danilowoz/wipe.css/blob/master/wipe.css#L6

But I don't have Figure element on my test: https://github.com/danilowoz/wipe.css/blob/master/test.html

Feel free to open a PR and test it :)

Falows!
